services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - DB_HOST=127.0.0.1
      - DB_PORT=3307
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/google-credentials.json  
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials:ro  
    networks:
      - backend
    depends_on:
      - cloud_sql_proxy
    restart: unless-stopped

  cloud_sql_proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.28.1
    container_name: cloud_sql_proxy
    command: 
      - "/cloud_sql_proxy"
      - "--instances=sohail-437105:europe-west3:sohail-ocv1=tcp:0.0.0.0:3307"
    ports:
      - "3307:3307"
    volumes:
      - ./credentials/google-credentials.json:/app/config/google-credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/google-credentials.json
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
