version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - DB_HOST=127.0.0.1
      - DB_PORT=3307
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}

    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: Eng#Data2024
        MYSQL_DATABASE: sohail_db
        MYSQL_USER: maram
        MYSQL_PASSWORD: Eng#Data2024


    volumes:
      - ./data:/app/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge