version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/google-credentials.json  
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials:ro  
    restart: unless-stopped
    command: >
      sh -c "
        if [ -n "$NGROK_AUTHTOKEN" ]; then
          ngrok config add-authtoken "$NGROK_AUTHTOKEN" &&
          ngrok http 8080 --domain=adapting-moccasin-vastly.ngrok-free.app &
        else
          echo 'Warning: NGROK_AUTHTOKEN not set. Skipping ngrok setup.'
        fi &&
        gunicorn --workers 4 --worker-class gevent --bind 0.0.0.0:8080 main:app
      "

volumes:
  data: